Prevent plugin name injections

diff --git a/.github/actions/get-wordpress-plugin-versions/action.yml b/.github/actions/get-wordpress-plugin-versions/action.yml
--- a/.github/actions/get-wordpress-plugin-versions/action.yml
+++ b/.github/actions/get-wordpress-plugin-versions/action.yml
@@ -24,8 +24,15 @@ runs:
     - name: Get plugin info
       id: get-plugin-info
       shell: bash
+      env:
+        WP_PLUGIN_SLUG: ${{ inputs.plugin-slug }}
       run: |
-        curl -s 'https://api.wordpress.org/plugins/info/1.0/${{ inputs.plugin-slug }}.json' > '${{ inputs.plugin-slug }}.json'
+        if [[ ! "$WP_PLUGIN"  =~ ^[a-z]([a-z0-9]|-|_)*[a-z]$ ]];
+        then
+          echo "Invalid plugin slug: $WP_PLUGIN_SLUG"
+          exit 1
+        fi
+        curl -s 'https://api.wordpress.org/plugins/info/1.0/$WP_PLUGIN_SLUG.json' > '$WP_PLUGIN_SLUG.json'
 
     - name: Get versions as JSON
       id: get-versions-json
